"""Tool registration. Importing this package triggers @mcp.tool decorators."""
from . import (  # noqa: F401
    audit_ledger,
    create_draft,
    create_template,
    get_draft,
    get_partner_state,
    import_markdown,
    list_drafts,
    list_due_touches,
    list_engagements,
    list_templates,
    log_contact,
    mark_sent,
    outreach_metrics,
    pipeline_snapshot,
    plan_quarter,
    render_template,
    set_outreach_stage,
    set_quarter_topic,
    update_draft,
    update_engagement,
    upsert_partner,
    # v1.2 — engagement & programme extension
    advance_engagement,
    approve_message,
    list_messages,
    list_pipeline,
    programme_status,
    queue_message,
    upsert_engagement,
    upsert_org,
    # v1.3 — documents & interview transcripts
    attach_file,
    get_attachment,
    get_interview,
    list_attachments,
    list_interviews,
    log_interview,
    set_transcript,
    # comp comparison
    compare_comp,
    delete_comp_scenario,
    list_comp_scenarios,
    upsert_comp_scenario,
)
